const database = require('./database');

const idToken = 'eyJhbGciOiJSUzI1NiIsImtpZCI6IjRhOWEzMGI5ZThkYTMxNjY2YTY3NTRkZWZlZDQxNzQzZjJlN2FlZWEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGhvb21pbi1zcG90aWZ5LWFwcCIsImF1ZCI6InRob29taW4tc3BvdGlmeS1hcHAiLCJhdXRoX3RpbWUiOjE1NzQ3ODUyNTksInVzZXJfaWQiOiJzcG90aWZ5OnVzZXI6c2lybWlzdGVyeSIsInN1YiI6InNwb3RpZnk6dXNlcjpzaXJtaXN0ZXJ5IiwiaWF0IjoxNTc0Nzg1MjYwLCJleHAiOjE1NzQ3ODg4NjAsImVtYWlsIjoibnRvcnJlc3NtQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJudG9ycmVzc21AZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.B0xfckPT1USb3JCs4qG4rjMnBF7YgfvnaQ16r-fM-jtvytCum50j-OuTnTJOXy_prgz8pNLhWnFI9wU-GA0FBVbWnWmHUaxRWJX7mZA_Ul4BYibfFLYI1KehTJbZOMdtTlCooMHuxlm-olnmOUk0PrGZYvhFipLNLEvLOaxiAQnKZs-d5SoEHNSuxJuffxNAapAqguNpJ0nEiK4gK5QpazttyB4HeHSraVewHT_XNlkbwmMOKEvT0COoAMCeTj0dU7eA8yIe2N0wfY0kSPCX9apWXy7QipIQ6wDPvXSjPBbYwcN7aOqVisBbr8eYkUWGdQijq3loi0zjDYNzpKiIeQ';

database.createParty(idToken, 'Test Name')
.then(party => {
	console.log(party);
	return party;
})
.catch(error => {
	console.log(error);
})